### ISSUE TITLE
The module 'xx/xx/../node_modules/@pokusew/pcsclite/build/Release/pcsclite.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 75

### ISSUE THREAD

**Issue by darkfiredarkhalo** [pokusew/node-pcsclite#32]
```
App threw an error during load
Error: The module '/xx/xx/.../node_modules/@pokusew/pcsclite/build/Release/pcsclite.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
```

**Comment by petrzjunior** [comment]
Hi @darkfiredarkhalo, thank you for the bug report! I am unable to reproduce the problem, so I would need a little help from you. It seems, that Node.js is complaining about the native library being built against different version than the the rest of your project.
Please try to rebuild and update all packages first.
```console
yarn rebuild
yarn install
```
or
```console
npm rebuild
npm install
```
If this doesn't solve the problem, please write down the version of Node.js and node-gyp you are using. Any information about used OS, your project setup and typical build workflow might be helpful as well.
