### ISSUE TITLE
Problem installing on Raspberry PI with Ubuntu 16.4 LTS

### ISSUE THREAD

**Issue by gibsodo** [pokusew/node-pcsclite#41]
Hi, i am using the nfc-pcsc package which includes this one here. It works fine under windows, but now iam trying to get it on a raspberry pi. I get the error, that file "winscard.h" is missing. Here is the full error message:

`> @pokusew/pcsclite@0.6.0 install /usr/local/bin/shelfcam/node_modules/@pokusew/pcsclite
> node-gyp rebuild

make: Entering directory '/usr/local/bin/shelfcam/node_modules/@pokusew/pcsclite/build'
  CXX(target) Release/obj.target/pcsclite/src/addon.o
In file included from ../src/addon.cpp:1:0:
../src/pcsclite.h:9:22: fatal error: winscard.h: No such file or directory
compilation terminated.
pcsclite.target.mk:127: recipe for target 'Release/obj.target/pcsclite/src/addon.o' failed
make: *** [Release/obj.target/pcsclite/src/addon.o] Error 1
make: Leaving directory '/usr/local/bin/shelfcam/node_modules/@pokusew/pcsclite/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.1.19-v7+
gyp ERR! command "/root/.nvm/versions/node/v12.18.3/bin/node" "/root/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/bin/shelfcam/node_modules/@pokusew/pcsclite
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN shelfcam-testing@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pokusew/pcsclite@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pokusew/pcsclite@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by gibsodo** [comment]
Solved it by installing some packages:
libpcsclite1, pcscd and libpcsclite-dev.
